#!/bin/bash
#
# chkconfig: 3 30 70
# description: Starts and stops the ssh remote tunnel

# Source function library.
if [ -f /etc/init.d/functions ] ; then
    . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
    . /etc/rc.d/init.d/functions
else
    exit 1
fi

# Avoid using root's TMPDIR
unset TMPDIR

RETVAL=0
BINFILE=/usr/bin/ssh
PIDFILE=/var/run/ssh_tunnel.pid
KIND=ssh_remote_tunnel

start() {
    /bin/echo -n $"Starting $KIND services: "
    CMD="$BINFILE"' -afgNTR 0.0.0.0:{{BIN_REMOTE_TUNNEL_REMOTE_PORT}}:localhost:{{BIN_REMOTE_TUNNEL_LOCAL_PORT}} {{BIN_REMOTE_TUNNEL_REMOTE_USER}}@{{BIN_REMOTE_TUNNEL_REMOTE_HOST}} -o ServerAliveInterval=300 -o TCPKeepAlive=yes -o ServerAliveCountMax=100'
    /bin/su -l {{DEPLOY_USER}} -c "$CMD"
    PID=`/bin/ps aux|/bin/grep "$CMD"|/bin/grep -v 'grep'|/usr/bin/awk '{print $2}'`
    /bin/echo $PID > $PIDFILE
    RETVAL=$?
    success
    /bin/echo
    [ $RETVAL -eq 0 ]
        RETVAL=1
    return $RETVAL
}

stop() {
    /bin/echo -n $"Shutting down $KIND services: "
    kill -QUIT `cat $PIDFILE`
    RETVAL=$?
    success
    /bin/echo
    [ $RETVAL -eq 0 ] && rm -f $PIDFILE 
    return $RETVAL
}

restart() {
    stop
    start
}

status() {
    if [ ! -r $PIDFILE ]; then
        /bin/echo "ssh remote tunnel is stopped"
        exit 0
    fi

    PID=`cat $PIDFILE`
    if ps -p $PID | grep -q $PID; then
        /bin/echo "ssh remote tunnel (pid $PID) is running..."
    else
        /bin/echo "ssh remote tunnel dead but pid file exists"
    fi
}

# Check that we can write to it... so non-root users stop here
[ -w $BINFILE ] || exit 4

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        /bin/echo $"Usage: $0 {start|stop|restart|status}"
        exit 2
esac

exit $?