#!/bin/bash
#
# chkconfig: 3 21 79
# description: Starts and stops the php-fpm server

# Source function library.
if [ -f /etc/init.d/functions ] ; then
    . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
    . /etc/rc.d/init.d/functions
else
    exit 1
fi

# Avoid using root's TMPDIR
unset TMPDIR

RETVAL=0
BINFILE={{INSTALL_DIR_BIN_BIN}}/sbin/php-fpm
PIDFILE={{INSTALL_FILE_BIN_PID}}
CFGFILE={{INSTALL_DIR_BIN_BIN}}/etc/php-fpm.conf
KIND=php-fpm

start() {
    /bin/echo -n $"Starting $KIND services: "
    $BINFILE
    RETVAL=$?
    success
    /bin/echo
    [ $RETVAL -eq 0 ]
        RETVAL=1
    return $RETVAL
}

stop() {
    /bin/echo -n $"Shutting down $KIND services: "
    kill -QUIT `cat $PIDFILE`
    RETVAL=$?
    success
    /bin/echo
    [ $RETVAL -eq 0 ] && rm -f $PIDFILE 
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    /bin/echo -n $"Reloading $CFGFILE: "
    kill -USR2 `cat $PIDFILE`
    RETVAL=$?
    success
    /bin/echo
    return $RETVAL
}

configtest() {
    $BINFILE -t
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        /bin/echo Syntax OK
        return $RETVAL
    fi
    return $RETVAL
}

status() {
    if [ ! -r $PIDFILE ]; then
        /bin/echo "php-fpm is stopped"
        exit 0
    fi

    PID=`cat $PIDFILE`
    if ps -p $PID | grep -q $PID; then
        /bin/echo "php-fpm (pid $PID) is running..."
    else
        /bin/echo "php-fpm dead but pid file exists"
    fi
}

# Check that we can write to it... so non-root users stop here
[ -w $BINFILE ] || exit 4

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    reload)
        reload
        ;;
    configtest)
        configtest
        ;;
    status)
        status
        ;;
    *)
        /bin/echo $"Usage: $0 {start|stop|restart|reload|status|configtest}"
        exit 2
esac

exit $?