#!/bin/sh

DOMAIN='jxu.life'
DOMAIN_REG='jxu\.life'

ENV_USER='app'
ENV_GROUP='app'

VERSION_NGINX='1.6.2'
VERSION_PHP='5.6.0'
VERSION_MYSQL='5.6.21'
VERSION_BIND='9.10.2'

BIN_NGINX='nginx-'$VERSION_NGINX
BIN_PHP='php-'$VERSION_PHP
BIN_MYSQL='mysql-'$VERSION_MYSQL'-linux-glibc2.5-x86_64'
BIN_BIND='bind-'$VERSION_BIND

URL_BINCODE_NGINX='http://nginx.org/download/'$BIN_NGINX'.tar.gz'
URL_BINCODE_PHP='http://cn2.php.net/distributions/'$BIN_PHP'.tar.gz'
URL_BINCODE_MYSQL='http://cdn.mysql.com/archives/mysql-5.6/'$BIN_MYSQL'.tar.gz'
URL_BINCODE_BIND='ftp://ftp.isc.org/isc/bind9/9.10.2/'$BIN_BIND'.tar.gz'

INSTALL_DIR_DATA='/data'
INSTALL_DIR_BIN=$INSTALL_DIR_DATA'/bin'
INSTALL_DIR_LOG=$INSTALL_DIR_DATA'/logs'
INSTALL_DIR_APP=$INSTALL_DIR_DATA'/app'

INSTALL_DIR_NGINX=$INSTALL_DIR_BIN'/'$BIN_NGINX
INSTALL_DIR_PHP=$INSTALL_DIR_BIN'/'$BIN_PHP
INSTALL_DIR_MYSQL=$INSTALL_DIR_BIN'/'$BIN_MYSQL
INSTALL_DIR_BIND=$INSTALL_DIR_BIN'/'$BIN_BIND

LOG_DIR_NGINX=$INSTALL_DIR_LOG'/nginx'
LOG_DIR_PHP=$INSTALL_DIR_LOG'/php-fpm'
LOG_DIR_MYSQL=$INSTALL_DIR_LOG'/mysql'
LOG_DIR_BIND=$INSTALL_DIR_LOG'/bind';

PID_PATH_NGINX=$LOG_DIR_NGINX'/nginx.pid'
PID_PATH_PHP=$LOG_DIR_PHP'/php-fpm.pid'
PID_PATH_MYSQL=$LOG_DIR_MYSQL'/mysql.pid'
PID_PATH_BIND=$LOG_DIR_BIND'/bind.pid'

SSHD_PORT=*
MYSQLD_PORT=*

COMPILE_NGINX='./configure --prefix='$INSTALL_DIR_BIN/$BIN_NGINX' --user='$ENV_USER' --group='$ENV_GROUP' --with-http_ssl_module --with-http_gzip_static_module  --with-http_stub_status_module --with-pcre'
COMPILE_PHP='./configure --prefix='$INSTALL_DIR_BIN/$BIN_PHP' --with-fpm-user='$ENV_USER' --with-fpm-group='$ENV_GROUP' --enable-fpm --disable-short-tags --disable-ipv6 --with-zlib --with-pdo-mysql --enable-mbstring --with-openssl --enable-zip --with-mcrypt'
COMPILE_MYSQL=''
COMPILE_BIND='./configure --prefix='$INSTALL_DIR_BIN/$BIN_BIND' --enable-largefile --enable-threads'

EXEC_DIR_BASE=$(cd "$(dirname "$0")"; pwd)
EXEC_DIR_BINCODE=$EXEC_DIR_BASE'/tar'
EXEC_DIR_BINCONF=$EXEC_DIR_BASE'/bin_conf'
EXEC_DIR_SHELL=$EXEC_DIR_BASE'/shell'

BIN_VAR="DOMAIN DOMAIN_REG \
ENV_USER ENV_GROUP \
VERSION_NGINX VERSION_PHP VERSION_MYSQL VERSION_BIND \
BIN_NGINX BIN_PHP BIN_MYSQL BIN_BIND \
URL_BINCODE_NGINX URL_BINCODE_PHP URL_BINCODE_MYSQL URL_BINCODE_BIND \
INSTALL_DIR_DATA INSTALL_DIR_BIN INSTALL_DIR_LOG INSTALL_DIR_APP \
INSTALL_DIR_NGINX INSTALL_DIR_PHP INSTALL_DIR_MYSQL INSTALL_DIR_BIND \
LOG_DIR_NGINX LOG_DIR_PHP LOG_DIR_MYSQL LOG_DIR_BIND \
PID_PATH_NGINX PID_PATH_PHP PID_PATH_MYSQL PID_PATH_BIND \
SSHD_PORT MYSQLD_PORT"

CFG_VAR="$BIN_VAR \
COMPILE_NGINX COMPILE_PHP COMPILE_MYSQL COMPILE_BIND \
EXEC_DIR_BASE EXEC_DIR_BINCODE EXEC_DIR_BINCONF EXEC_DIR_SHELL"
