export LANG="zh_cn.utf-8"
export HISTTIMEFORMAT='%F %T '

USER_IP=`who -u am i 2>/dev/null| awk '{print $NF}' |sed -e 's/[()]//g'`
if [ $USER_IP = '' ]; then
    USER_IP=`hostname`
fi

HISDIR=~/.history
if [ ! -d $HISDIR ]; then
    mkdir $HISDIR
fi

DT=`date +%Y%m%d`
export HISTFILE="$HISDIR/$DT.$USER_IP.bash_history"
