source $EXEC_DIR_ROOT'/config'
source $EXEC_DIR_ROOT'/inc/functions.sh'

debug 'UID is: '"$UID"'.'
if [ $UID -ne 0 ] ; then
    error 'You should run as root!!!'
fi

#create bin configure variables
BIN_CONFIGURE_FRAME_VARS='BIN_NAME BIN_VERSION ENV_USER ENV_GROUP DEBUG COMMON_LIB 
INSTALL_DIR_LOCAL_DATA INSTALL_DIR_REMOTE_DATA INSTALL_DIR_BIN INSTALL_DIR_LOG INSTALL_DIR_APP
EXEC_CURRENT_DIR EXEC_DIR_ROOT EXEC_DIR_TAR EXEC_DIR_TEMP EXEC_DIR_ASSEMBLE EXEC_DIR_ASSEMBLE_BIN_VERSION 
BIN_FULL_NAME BIN_DOWNLOAD_URL BIN_CODE_TAR BIN_CODE_DIR BIN_COMMON_LIB'
