#!/bin/bash

errors=$({{sBinInstallDir}}/sbin/php-fpm --fpm-config "{{sBinInstallDir}}/etc/php-fpm.conf" -t 2>&1 | grep 'ERROR' || true);
if [ -n "$errors" ]; then
    echo 'Please fix your configuration file...'
    echo "$errors"
    exit 1
fi
exit 0