#!/bin/bash

#do some install scripts

showInfo 'install node start.'
    createDir $sBinInstallDir 'y'
    /bin/cp -R $sExecTempDir$sBinSourceCodeSubDir $sBinInstallRootDir
showInfo 'install node successfully.'