#!/bin/bash

#do some install scripts

showInfo 'configure nginx installation start.'
cd $sExecTempDir$sBinSourceCodeSubDir
./configure --prefix=$sBinInstallDir --pid-path=$sBinPidInstallFile --user=$sEnvUser --group=$sEnvGroup --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --with-pcre
if [ 0 -eq $? ]; then
    showInfo 'configure nginx installation successfully.'
else
    showError 'configure nginx installation failed.'
fi

showInfo 'compile and install nginx start.'
/usr/bin/make && /usr/bin/make install
if [ 0 -eq $? ]; then
    showInfo 'compile and install nginx successfully.'
else
    showError 'compile and install nginx failed.'
fi