#!/bin/bash

#do some install scripts

showInfo 'configure php-msgpack installation start.'

cd $sExecTempDir$sBinSourceCodeSubDir

$sBinPhpInstallDir'/bin/phpize'
./configure --with-msgpack --with-php-config=$sBinPhpInstallDir'/bin/php-config'
if [ 0 -eq $? ]; then
    showInfo 'configure php-msgpack installation successfully.'
else
    showError 'configure php-msgpack installation failed.'
fi
showInfo 'compile and install php-msgpack start.'
/usr/bin/make && /usr/bin/make install
if [ 0 -eq $? ]; then
    showInfo 'compile and install php-msgpack successfully.'
else
    showError 'compile and install php-msgpack failed.'
fi